# CodeRabbit Configuration
language: "en"
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
chat:
  auto_reply: true

